### ISSUE TITLE
KaryScript's Grammar Design Survey

### ISSUE THREAD

**Issue by pouyakary** [karyfoundation/karyscript#1]
# What is this?
KaryScript is an experimental language in its early phases of design (each part that gets complete in the design drafts gets implemented imminently in the grammar file. once the grammar is complete the compiler is going to be written).

KaryScript's goal is only one thing: "a more readable syntax for JavaScript". Now JavaScript is already a very good language but can we improve the syntax's readability? That's what this whole experiment is all about. Kary Foundation has proved to be able to take consistency and code beauty reach a new level where no other organization or individual has ever taken and now with a much better syntax we want to complete that idea.

This is a survey like an issue to ask your opinion on what you love about language's syntax. There are things we want KaryScript to have and there are things that we may have no idea about. Tell as what are your thoughts and ideas. Maybe they get accepted and you get to have a language that has exactly what you want from its syntax.

# Design Principles
- `,`s are evil. We want a language that has no commas what so ever.
- The unnecessary syntax must be removed. (ex. in C you really don't need parentheses for `if` the compiler can simple understand: `if ... {` whiteout having to have `if ( ... ) {`)
- Wildcards are horrible and if possible we want one character grammars to be removed from the multi-line grammars. (so for example instead of having `}` we can have `end`. This is more readable.
- Binary operators are bad. S-Expressions are much more clear and concise (thinking lispy...)
- Unnecessary keywords are bad. For example why having `let` and `var`. Compiler and place them well. We can have `def` for all `let`, `var` and even `function` declarations.
- `camelCase` and `_underscoe_names` are ugly. we want `dash-names`

# Ideas
### Everything is defined with `def`
```
def m = 4
def sum = [ x y => (+ x y) ]
def some-function  a  b:
   (* a b) > (+ 5) > return
end
```

### Pipes are more readable
This syntax:
```
return func1( func2( func3( a b ), 2 ), 3 )
```
Can be written as
```
(func3 a b) > (func2 2) > (func1 3) > return
```

### S-Expression
```
func( a, b, c ) 
```
Can be written as
```
(func a b c)
```
As to talk with @keyvank operators are used with algebraic system with forced `( left operator right )` grammar:
```
1 + 2 * 3 ==> ( 1 + ( 2 * 3 ) )
```

### Names and Identifiers
camelCase namings are horrible, they hurt the eye and makes it very difficult to read. Also underscore based names are ugly so people go with camelCase and well... But the grammar here is designed around in a way to let you have a much better naming way:
```
kary.terminal.parseInput ==> kary/terminal/parse-input
```

### Lambda Expressions
```
( something/map [ x => (* x 2) ] )
```
For the inline we have the lambdas enclosed with braces this way we can avoid `,` (have we mentioned that they are devil?)
```
[ x y z => (* x (+ y z) ) ]
```

### Better loops
```
for x in [ 1 2 3 ]:
   (console/log x)
end

for x of [ 1 2 3 ]:
   (console/log x)
end

for 1 to 10:
   (console/log "hello")
end

for 1 to 10 as index:
   (console/log index)
end

while (< 2 x):
   (console/log "hmmm");
end
```

### Strings
```
def x = "2 + 3 = #{ ( + 2 3 ) }"
```
- ideas for the string interpolation are [ `#{ ... }`  `\( ... )` ]. now `\( ... )` is easier to write but `#{ ... }` is better to see.

### Comments
```
(* multi line *)
-- inline
```
- `--` is very good because needs no `shift`

### Objects and Arrays
You get it, we hate having `,`s
```
def arr = [ 1 2 3 ]
def obj = {
    a = 1
    b = 2
    c = 3
}
```

### Imports
`not sure` because of the object notation
```
from "awesome" import { x y z }
```
- It must be reversed so we can have intelliSense in the future

**Comment by pouyakary** [comment]
by @keyvank on #2 

Great idea! Keep up the good work ;)

1- I can't understand why commas are evil?
2- I think using the "end" keyword instead of "}" has no advantages but time consuming. I would prefer Pythonic style of code blocks!
3- dash-names?! What's wrong with the underscores? I think dash-names can be easily confused with the minus operator.
4- Why Haskell-style operators?

**Comment by pouyakary** [comment]
@keyvank
1. At the lexical level they play no role so by removing them it can become a bit cleaner: `[ 1 2 3 ]` instead of `[ 1, 2, 3 ]` is much more readable. And in places like JSON a tiny comma breaks the whole thing sometimes.
2. End keyword's point mostly is because of it's length and ergonomics. At KF we have this special commenting system (you can [check this link](https://github.com/karyfoundation/comment/blob/master/Core/UI.ts#L887-L891) to see why they are to small to be noticeable with our codes.) Also one point in the ergonomic tying is to avoid using the `shift` modifier.
3. Dash names are okay. As for compatibility with JavaScript tools it's only an addition you can use it and you can ignore it. Subtraction operator is fine because we use _Polish Notation_ it will never get confused. Dash names are very popular in other languages where it's lexically possible. One other thing that may come to the language is Arendelle naming system where you even get to have spaces in the names. And the language is currently designed in a way that keeps it possible to have Arendelle names too.
4. Constancy. This: `1 + 2 ^ 3 * 4 / 3` can be simply become confusing. Most modern basic parsers have 18+ levels of operator priority. This easily gets complicated for the user. However a well placed parentheses like forces constancy `(+ 1 (^ 2 (* 3 4)))`. While many languages try to have the algebra-like notation, most language designer say it's better to go with polish notation.

Now while all of these are based on researches and philosophies from Tulip, Swift, Lua, Ruby, TypeScript, Scheme, Racket, Clojure, Go, Rust and even Arendelle  (as of now). Many of them can be heavily simply based on taste. Hence arguments can sometime become like Vim vs Emacs.

So here comes two poins:
0. The language can decide a bit for the user. If we design the language towards readability it forces readability.
1. This survey mostly targets new ideas on the grammar. more than this talk about syntaxes that you would want to have on a language

**Comment by keyvank** [comment]
Why don't we just force the user to use parenthesis in regular algebra-like notations?
(+ 1 (^ 2 (* 3 4) ) )    ===>   (1 + (2 ^ (3 * 4) ) )

**Comment by pouyakary** [comment]
@keyvank that's also possible but it's less powerful. You will no longer have things like: `1 + 2 + 3` and `(+ 1 2 3)`. But that's good idea. we can have that.

`IMPLEMENTED` At commit [1430541](https://github.com/karyfoundation/karyscript/commit/14305415b4dd2a2eb48231d0da5e25fe1e0e5dba)

However it has problems with `dash-naming` so I have to think about how to fix that. And it's a potential subject of being removed as `dash-naming` is one of the fundamental parts of the language. I may add Arendelle namings that may result on something like this:
```
( @some name with spaces in the name + @some other name also with spaces )
```
But with dash names something like:
```
( dash-name )
```
Is not okay and only
```
( dash - name )
```
For now I'm forcing spaces on operators but that still is really not good for reading.

It can also get better by polish notations that have names like:
```
(sub 4 (sum 2 3 ))
```

**Comment by ghost** [comment]
*Sorry if I'm not allowed to comment but I'm really excited about this*.

Making `Javascript` more readable is a great idea, but I really don't think the current design is the way to go. Some parts are scary: I mean how could `[1 variable {object} [otherArray]]` be more readable than `[1, variable, {object}, [otherArray]]` ? try reading a book without punctuation, it'll be really incoherent.

If I had the chance to suggest, my suggestion would be:

- Keep the function side of the language: `pipes`, `lambdas'`, `list comprehension`, `S expressions`, etc.., they are really awesome.
- Remove `def`, personally I think that keyword is very formal and, how should I put this, very strict. `let` is by far more readable.
- Bring commas' back to life.
- Every programmer on earth is used to `.` for indicating property/members.
- Every Javascript programmer and library use camelCase, designing for them is crutial. same goes for `JSON`.
- `end` reminds of pascal and dark ages, **please** remove it. Indentation` is better.
- `import` expression are sexy, `export` and `export as` will be even better.
- Comment syntax is sexy too.
- Any plans for classes ? Decorators ? Destructuring ?
- A type system will be kickass for readability.
- Many library are doing great in web dev, supporting some of them natively can be a great feature. Something as simple as `Redux` will be great.

Putting that all together and you get a language like:
```javascript
from HTML import {div, h1, p, input, createStore, combineReducers, HTML}

let state = {
    header: "Introduction",
    paragraph: "This is a nice way to represent model, actually similar to the one used in elm and possible thanks to S-Expressions, probably the major different is the possible to overload function and be more user-friendly",
    note: "The model is a lambda function that takes a state and re-evaluates the whole expression to fit the state",
    submit: "Lovely",
    likes: 10
    comments: ["Cool", "Great", "Awesome", "Shitty"]
}

let model = state => div {class: "container"} [
    h1 state.header,
    div [
        p state.paragraph,
        p {class: 'sidenote'} state.note
    ],
    input {type: 'submit', value: state.submit},
    i {class: 'fa fa-thumb-up'} state.likes,
    [div {class "comment"} [p text] | text in state.comments], (*List comprehension syntax*)
];

let addLikeReducer = (likes, action) => if (== action.type 'addLike') then (+ 1 likes) else likes,
    addCommentReducer = (state, action) => if (== action.type 'addComment') then {state | comments.push action.comment} else state,
    store = createStore (combineReducers {'likes': addLikeReducer 'comments': addCommentReducer}) state

store.subscribe () => HTML.render (model store.getState)

export {
    addLike: () => store.dispatch({type: 'addLike'}),
    addComment: (playload) => store.dispatch({type: 'addComment', payload})
} as App
```
I'd like to know what you think, and thanks for your time.

**Comment by pouyakary** [comment]
@Noctisdark 
 thanks a lot for your interest! I got so little contribution on this survey here that I gave it up and the language changed a lot since then. This is as much of the language that is implemented:

```
//
// Copyright © 2017-present Kary Foundation, Inc. All rights reserved.
//   Author: Pouya Kary <k@karyfoundation.org>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//

//
// ─── DEFS ───────────────────────────────────────────────────────────────────────
//

    def x = (mul 11 (sum 5 6))
    def y = (mul 34 (sum 5 (foo-bar 4 5)))
    def m n k

//
// ─── QUERY SELECTORS ────────────────────────────────────────────────────────────
//

    x = [ y | 1 ]
    x = [ y | "hello" ]
    x = [ y | hello/world ]
    x = [ y | z => (div z 3) -> (> 3 %) ]

//
// ─── ASSIGNS ────────────────────────────────────────────────────────────────────
//

    m = 5
    x/y/z = (foo-bar 5 on)

    hello /= (replace "hello", "world")

//
// ─── OPERATIONS ─────────────────────────────────────────────────────────────────
//

    con f = (and on off)
    con number255 = 0xff

    (console/log (x) -> (div % 2))
    (foo-bar)

//
// ─── ARRAYS ─────────────────────────────────────────────────────────────────────
//

    x = [ 1 2 "hello world" (x)->(y) ]

//
// ─── SETS ───────────────────────────────────────────────────────────────────────
//

    y = {1 2 3}

//
// ─── MAP ────────────────────────────────────────────────────────────────────────
//

    z = { a: 1, (f) -> (g): "hello" }  

//
// ─── OBJECTS ────────────────────────────────────────────────────────────────────
//

    y = [
        a: 1, b: "hello"
        c: (x) -> (y) -> (div % 2)
        d: [ hello: "hello" ]
    ]

    z = [:]

//
// ─── FUNCTIONS ──────────────────────────────────────────────────────────────────
//

    export def man-man:
        def SecondLevel:
            throw (foo 10 20) -> (div % 5)
        end
        def something = 5
    end

//
// ─── TABLES ─────────────────────────────────────────────────────────────────────
//


    con norah-jones-best =
        | name                  | album                 | stars     |
        |-----------------------|-----------------------|-----------|
        | "Those Sweet Words"   | "Feels like home"     |     5     |
        | "Shoot The Moon"      | "Come Away with Me"   |     5     |
        | "Come Away with Me"   | "Come Away with Me"   |     4     |
        | "Sunrise"             | "Feels like home"     |     3     |


    con languages =
        | #         | name          | format                        |
        |-----------|---------------|-------------------------------|
        | kk        | "KaryScript"  | ".kk"                         |
        | orchestra | "Orchestra"   | ".orchestra"                  |
        | arendelle | "Arendelle"   | [ ".arendelle", ".space" ]    |
        | numerax   | "numeraX"     |                               |
        | pageman   | "Pageman"     | ".pageman"                    |

//
// ─── LAMBDA ─────────────────────────────────────────────────────────────────────
//

    def lambda = [ p1 p2 p3 => (sum p1 p2) -> (mul % p3) -> (div 4 %) ]

//
// ─── PIPE ───────────────────────────────────────────────────────────────────────
//
        
    def cool = (x) -> (div % 2) -> (z) ->
            (mul % 5) -> (foo-bar) -> (go)

//
// ─── STRING INTERPOLATION ───────────────────────────────────────────────────────
//

    def str = "2 + 3 = #(sum 2 3)"

    def s1 = "this is a text"
    def s2 = "#(sum 1 2)"
    def s3 = "text with interpolation: #(mul (x)->(y) 4)"

//
// ─── IFS ────────────────────────────────────────────────────────────────────────
//

    if on:
        (foo 1)
    also unless (y):
        (foo 2)
    also if (x) -> (z):
        (foo 3)
    else
        (foo 4)
    end

    x = (eq 1 1)? on ! off

//
// ─── WHILE ──────────────────────────────────────────────────────────────────────
//

    while not off:
        (console/log "hello world")
    end

//
// ─── ASYNC AWAIT ────────────────────────────────────────────────────────────────
//

    async delay time:
        return new (Promise [ res => (setTimeout res time) ])
    end

    await (delay 5000)

//
// ─── CLASS DECLARATIONS ─────────────────────────────────────────────────────────
//

    class Foo:
        def constructor x:
            this/x = x
        end
    end

    class X extends Y:
        def something y:
            (foo)
        end
    end

//
// ─── OBJECT DECLARATIONS ────────────────────────────────────────────────────────
//

    object x:
        y: 2
        z: (f) -> (g)
    end

    export template x:
        y: 5
        z: 523
    end

//
// ─── FOR LOOPS ──────────────────────────────────────────────────────────────────
//

    for (x):
        (foo)
    end

    for (x) up to (y):
        (foo)
    end 

    for (x) up to 200 step (z):
        (do-something)
    end

    for (x) via index:
        (foo index)
    end

    for (foo) down to (bar):
        (nice)
    end

    for x of (xs):
        (foo x)
    end

//
// ─── CLONE ──────────────────────────────────────────────────────────────────────
//

    def y = clone x

//
// ─── SWITCH ─────────────────────────────────────────────────────────────────────
//

    switch x:
        case 1 2 (x):
            (foo)
        case (n) -> (m):
            (foo-bar)
        else
            (bar)
    end

// ────────────────────────────────────────────────────────────────────────────────
```

And there [ideas and todo list](https://github.com/karyfoundation/karyscript/blob/master/docs/ideas.md) so you can know what's to come.


Now to your bulletins:

#### Commas
Personally I preferred commas not to exists. But as you know it's an experimental language and will change as to find it's shape. One of the things that happened in between was to make them optional. Now in every sequence they are optional:

```
(foo 1, 2, 3)
```
So no problem with that


#### Imports
There will be a grammar called `use` and I'm still thinking about it, but the general look will be:
```
use fs, path
```
which compiles to:
```
import * as fs from 'fs';
import * as path from 'path';
```
or:
```
const fs = require('fs');
const path = require('path');
```
based on your preferences.

And things like:
```
use a, b, c from d
```
It's design still lacks many different ways of importing so I haven't implemented it yet.

#### Class are simple like JavaScript:
```
class x extends y:
   def contractor:
       (this/foo)
   end
end
```
I haven't really fully thought about classes right. But decorators will be used as function keys:
```
@readonly def foo:
    (bar)
end
```
About mixins ... I have no idea! I'm thinking about it

#### `end` and indentation.
I know. having end is not as pretty as doing it with indentation. However, there is a "BUT" here.
I don't know much much you know about Kary Foundation and our way of coding. We have [this special way of comments (KFCS)](https://github.com/karyfoundation/comment/wiki/Section-&--Line-Comments). If you look you see our comments cause one level of additional indentation. Now these things can't be there if you have an indentation sensitive language. And if I add our comments as a special language grammar and tell the compiler to understand it's indentation, someone else will create a coding style that won't work with this compiler.

Furthermore there are many cases in which this spaces are bad. I agree they are fun. But bad for when you wanna have control over your code's look and style. Also I love `end` keyword. One of my dreams was to have the `end` keyword.

#### Types
Types are the best thing to have, I totally agree. but they are very very very hard to implement. There is however one solution: Using Flow or TypeScript in it's backend to have them check the types. What is needed in here is a code mapping system and I'm thinking about it's design. So maybe it get into the language. Problem is with their notation. I hope I find a way to keep the language simple but with types.

#### Supporting special libraries
that is very tricky. One thing for sure is that it will have JSX support. However other libraries come and go so I don't think if having a language grammar for them would be really good. I don't it will even have native features for Kary Framework. But we have to see. I have this idea about making shortcuts for these stuff so everyone can have some kind of grammar for their favorite stuff. But it's hard to think how it should look and what features it should have.

#### List Comprehensions
I love them and I have some plans for them.

#### Your Code and Language Look
There are different tastes when it comes to syntax. And yours is so much like something in between of CoffeeScript / Elm / Haskell / Ml and JS itself. Mine is a bit like VB, Ruby and Tulip in general. So that's why I mostly prefer using words like `end`.

I know the look of KaryScript might be strange a bit. odd and as it's a matter of taste I don't think if it's worthy of discussing the look.

However there are ideas about language features which can be really good. And I'm really looking for those suggestions here.

**Comment by ghost** [comment]
Sounds pretty neat, thanks for the reply, excited for the release :+1:.

**Comment by pouyakary** [comment]
@Noctisdark hoping you like it :D
