### ISSUE TITLE
Comments on Design Principles

### ISSUE THREAD

**Issue by keyvank** [karyfoundation/karyscript#2]
Great idea! Keep up the good work ;)

1- I can't understand why commas are evil?
2- I think using the "end" keyword instead of "}" has no advantages but time consuming. I would prefer Pythonic style of code blocks!
3- dash-names?! What's wrong with the underscores? I think dash-names can be easily confused with the minus operator.
4- Why Haskell-style operators?

**Comment by pouyakary** [comment]
Okay. Let's have thing conversation where it belongs at #1
